"""Add multi-unit options to Listing model

Revision ID: c4bf850904ad
Revises: 
Create Date: 2025-05-09 04:21:54.246659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4bf850904ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_bedrooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_bedrooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_bathrooms', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_bathrooms', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_multi_unit', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('unit_options', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('unit_options')
        batch_op.drop_column('is_multi_unit')
        batch_op.drop_column('max_bathrooms')
        batch_op.drop_column('min_bathrooms')
        batch_op.drop_column('max_bedrooms')
        batch_op.drop_column('min_bedrooms')

    # ### end Alembic commands ###
